import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "My Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="flex m-2 space-x-8 w-full place-content-center">
          <Link
            href="/ssg"
            className="flex w-14 border-4 border-teal-300 justify-center cursor-pointer"
          >
            SSG
          </Link>
          <Link
            href="/isr"
            className=" flex w-14 border-4 border-emerald-300 justify-center cursor-pointer"
          >
            ISR
          </Link>
          <Link
            href="/ssr"
            className="flex w-14 border-4 border-indigo-300 justify-center cursor-pointer"
          >
            SSR
          </Link>
          <Link
            href="/csr"
            className="flex w-14 border-4 border-fuchsia-300 justify-center cursor-pointer"
          >
            CSR
          </Link>
          <Link
            href="/"
            className="flex w-14 border-4 border-zinc-300 justify-center cursor-pointer"
          >
            Home
          </Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
